In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Indian_EV_Stations_Simplified.csv")

In [3]:
df.shape

(855, 9)

In [4]:
df.head()

,Station Name,City,State,Latitude,Longitude,Operator,Usage Type,Connector Type,Power (kW)
0,Tata.ev Luxon Motors - Tata Power,Edappally,Kerala,10.011485,76.311387,Tata Power,Public - Membership Required,CCS (Type 2),60.0
1,TML Sree Gokulam Motors - Tata Power,Edappally,Kerala,10.039155,76.315559,Tata Power,Public - Membership Required,CCS (Type 2),30.0
2,Tata.ev Gokulam Motors - Tata Power,Choornikkara,Kerala,10.081303,76.339462,Tata Power,Public - Membership Required,CCS (Type 2),60.0
3,Taj Cochin Internation Airport Hotel - Tata Power,Nedumbassery,Kerala,10.159995,76.390154,Tata Power,Public - Membership Required,CCS (Type 2),30.0
4,SAJ Earth Resort - Tata Power,Nedumbassery,Kerala,10.162224,76.384653,Tata Power,Public - Membership Required,CCS (Type 2),30.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 855 entries, 0 to 854
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Station Name    855 non-null    object
 1   City            855 non-null    object
 2   State           854 non-null    object
 3   Latitude        855 non-null    float64
 4   Longitude       855 non-null    float64
 5   Operator        855 non-null    object
 6   Usage Type      855 non-null    object
 7   Connector Type  855 non-null    object
 8   Power (kW)      853 non-null    float64
dtypes: float64(3), object(6)
memory usage: 60.2+ KB

In [6]:
df.isna().sum()

Station Name      0
City              0
State             1
Latitude          0
Longitude         0
Operator          0
Usage Type        0
Connector Type    0
Power (kW)        2
dtype: int64

In [7]:
(df == "  ").sum()

Station Name      0
City              0
State             0
Latitude          0
Longitude         0
Operator          0
Usage Type        0
Connector Type    0
Power (kW)        0
dtype: int64

In [8]:
df[(df["State"].isna()) | (df["Power (kW)"].isna())]

,Station Name,City,State,Latitude,Longitude,Operator,Usage Type,Connector Type,Power (kW)
543,Gandhi Nagar KSEB EVCS - ChargeMOD,Arpookara,Kerala,9.632684,76.524402,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,NaN
581,Muzhangodayil EVCS - ChargeMOD,Harippad,NaN,9.251674,76.487233,ChargeMod (IN),Public - Membership Required,CCS (Type 2),60.0
805,Silavattam Village,"Madurathakam, Chengalpattu Dt",Tamil Nadu,12.481488,79.862522,(Unknown Operator),"Private - For Staff, Visitors or Customers",Unknown,NaN

In [9]:
df.describe()

         Latitude   Longitude  Power (kW)
count  855.000000  855.000000  853.000000
mean    10.503103   76.533179   30.569871
std      2.054603    1.129636   19.908080
min      8.306584   74.202737    3.200000
25%      9.551795   76.183041   22.000000
50%     10.197144   76.388294   30.000000
75%     11.058305   76.743625   30.000000
max     28.706612   88.456284  150.000000

In [10]:
df[df.duplicated(keep = False)].tail(20)

,Station Name,City,State,Latitude,Longitude,Operator,Usage Type,Connector Type,Power (kW)
762,Kerala EV Vembayam,Thiruvananthapuram,Kerala,8.651755,76.927980,ChargeMod (IN),Public - Membership Required,CCS (Type 2),60.0
763,Kerala EV Vembayam,Thiruvananthapuram,Kerala,8.651755,76.927980,ChargeMod (IN),Public - Membership Required,CCS (Type 2),60.0
766,Club Mahindra Resort Poovar,Thiruvananthapuram,Kerala,8.306584,77.086086,Zeon Charging,Public - Membership Required,Type 2 (Tethered Connector),22.0
767,Club Mahindra Resort Poovar,Thiruvananthapuram,Kerala,8.306584,77.086086,Zeon Charging,Public - Membership Required,Type 2 (Tethered Connector),22.0
772,Hilton Garden Inn Trivandrum,Thiruvananthapuram,Kerala,8.499635,76.950299,Statiq (IN),Public - Membership Required,CCS (Type 2),60.0
773,Hilton Garden Inn Trivandrum,Thiruvananthapuram,Kerala,8.499635,76.950299,Statiq (IN),Public - Membership Required,CCS (Type 2),60.0
780,ChargeMOD EVCS Hub,Thiruvananthapuram,Kerala,8.550684,76.878488,ChargeMod (IN),Public - Membership Required,CCS (Type 2),60.0
781,ChargeMOD EVCS Hub,Thiruvananthapuram,Kerala,8.550684,76.878488,ChargeMod (IN),Public - Membership Required,CCS (Type 2),60.0
783,Delta Power Kulathoor,Thiruvananthapuram,Kerala,8.542037,76.875819,ChargeMod (IN),Public - Membership Required,CCS (Type 2),60.0
784,Delta Power Kulathoor,Thiruvananthapuram,Kerala,8.542037,76.875819,ChargeMod (IN),Public - Membership Required,CCS (Type 2),60.0
787,Alpha EVCS Yahoo Super Bazar,Thiruvanthapuram,Kerala,8.510832,76.904840,ChargeMod (IN),Public - Membership Required,CCS (Type 2),60.0
788,Alpha EVCS Yahoo Super Bazar,Thiruvanthapuram,Kerala,8.510832,76.904840,ChargeMod (IN),Public - Membership Required,CCS (Type 2),60.0
813,7 Star Green Veg Restaurant,Vaniyambadi,Tamil Nadu,12.646820,78.582690,Zeon Charging,Public,CCS (Type 2),60.0
814,7 Star Green Veg Restaurant,Vaniyambadi,Tamil Nadu,12.646820,78.582690,Zeon Charging,Public,CCS (Type 2),60.0
818,"Adyar Ananda Bhavan, Attur",Attur,Tamil Nadu,11.592000,78.627260,Zeon Charging,Public,CCS (Type 2),50.0
819,"Adyar Ananda Bhavan, Attur",Attur,Tamil Nadu,11.592000,78.627260,Zeon Charging,Public,CCS (Type 2),50.0
834,"Sree Saravana Bhavan, Sankagiri",Sangagiri,Tamil Nadu,11.486600,77.992260,Zeon Charging,Public,CCS (Type 2),30.0
835,"Sree Saravana Bhavan, Sankagiri",Sangagiri,Tamil Nadu,11.486600,77.992260,Zeon Charging,Public,CCS (Type 2),30.0
852,"SR Jungle Resort, Anaikatti",Anaikatti,Tamil Nadu,11.118480,76.759850,Zeon Charging,Public,Type 2 (Tethered Connector),22.0
853,"SR Jungle Resort, Anaikatti",Anaikatti,Tamil Nadu,11.118480,76.759850,Zeon Charging,Public,Type 2 (Tethered Connector),22.0

In [11]:
df.loc[15]

Station Name      TML Hyson Motors - Tata Power
City                                   Thrissur
State                                    Kerala
Latitude                              10.540423
Longitude                             76.189678
Operator                             Tata Power
Usage Type         Public - Membership Required
Connector Type                     CCS (Type 2)
Power (kW)                                 25.0
Name: 15, dtype: object

In [12]:
df.nunique()

Station Name      489
City              285
State              18
Latitude          500
Longitude         500
Operator           10
Usage Type          4
Connector Type      7
Power (kW)         21
dtype: int64

In [13]:
df.drop_duplicates(inplace= True)

In [14]:
df.shape

(789, 9)

In [15]:
df.isna().sum()

Station Name      0
City              0
State             1
Latitude          0
Longitude         0
Operator          0
Usage Type        0
Connector Type    0
Power (kW)        2
dtype: int64

In [16]:
df[df["State"].isna()]

,Station Name,City,State,Latitude,Longitude,Operator,Usage Type,Connector Type,Power (kW)
581,Muzhangodayil EVCS - ChargeMOD,Harippad,NaN,9.251674,76.487233,ChargeMod (IN),Public - Membership Required,CCS (Type 2),60.0

In [17]:
df[df["City"] == "Harippad"]

,Station Name,City,State,Latitude,Longitude,Operator,Usage Type,Connector Type,Power (kW)
581,Muzhangodayil EVCS - ChargeMOD,Harippad,NaN,9.251674,76.487233,ChargeMod (IN),Public - Membership Required,CCS (Type 2),60.0

In [18]:
df[df["Station Name"] == "Muzhangodayil EVCS - ChargeMOD"]

,Station Name,City,State,Latitude,Longitude,Operator,Usage Type,Connector Type,Power (kW)
581,Muzhangodayil EVCS - ChargeMOD,Harippad,NaN,9.251674,76.487233,ChargeMod (IN),Public - Membership Required,CCS (Type 2),60.0

In [19]:
df.drop(index= 581 , inplace  = True)

In [20]:
df.shape

(788, 9)

In [21]:
df[df["Power (kW)"].isna()]

,Station Name,City,State,Latitude,Longitude,Operator,Usage Type,Connector Type,Power (kW)
543,Gandhi Nagar KSEB EVCS - ChargeMOD,Arpookara,Kerala,9.632684,76.524402,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,NaN
805,Silavattam Village,"Madurathakam, Chengalpattu Dt",Tamil Nadu,12.481488,79.862522,(Unknown Operator),"Private - For Staff, Visitors or Customers",Unknown,NaN

In [22]:
df[(df["Operator"] == "ChargeMod (IN)") & (df["Connector Type"] == "GB-T DC - GB/T 20234.3")]

,Station Name,City,State,Latitude,Longitude,Operator,Usage Type,Connector Type,Power (kW)
256,Kanhangad KSEB EVCS - ChangeMOD,Kanhangad,Kerala,12.342505,75.112664,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,30.0
269,Manjapalam KSEB EVCS - ChargeMOD,Kannur,Kerala,11.878368,75.359526,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,30.0
283,Banasura Sagar KSEB EVCS - ChargeMOD,Padinjarathara,Kerala,11.672924,75.957306,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,30.0
297,Vythiri KSEB EVCS - ChargeMOD,Vythiri,Kerala,11.545754,76.039372,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,30.0
302,Thamarassery KESEB EVCS - ChargeMOD,Thamarassery,Kerala,11.444087,75.955877,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,15.0
319,Pavangad KSEB EVCS - ChargeMOD,Pavangad,Kerala,11.312412,75.758591,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,15.0
323,Gandhi Road KSEB EVCS - ChargeMOD,Kozhikode,Kerala,11.262784,75.768241,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,15.0
331,Tirur KSEB EVCS - ChargeMOD,Tirur,Kerala,10.916247,75.918287,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,15.0
339,Malappuram KSEB EVCS - ChargeMOD,Munduparamba,Kerala,11.054225,76.092143,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,15.0
362,Kulappully KSEB EVCS - ChargeMOD,Kulappully,Kerala,10.779746,76.285281,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,15.0
367,Koottanad KSEB EVCS - ChargeMOD,Kootanad,Kerala,10.758293,76.130366,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,22.0
376,Ponnani KSEB EVCS - ChargeMOD,Ponnani,Kerala,10.772703,75.947152,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,15.0
390,Vydyuthi Bhavan KSEB EVCS - ChargeMOD,Thrissur,Kerala,10.527795,76.205344,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,15.0
405,Valappad KSEB EVCS - ChargeMOD,Valappad,Kerala,10.401732,76.119335,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,22.0
410,Irinjalakkuda KSEB EVCS - ChargeMOD,Irinjalakkuda,Kerala,10.331423,76.215261,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,15.0
415,Vadakkenchery KSEB EVCS - ChargeMOD,Vadakkenchery,Kerala,10.597238,76.479849,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,15.0
446,North Paravoor KSEB EVCS - ChargeMOD,North Paravoor,Kerala,10.145633,76.256904,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,15.0
455,Kalamassery KSEB EVCS - ChargeMOD,Kalamassery,Kerala,10.053770,76.330868,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,15.0
464,Kaloor KSEB EVCS - ChargeMOD,Kaloor,Kerala,10.000241,76.298430,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,15.0
468,Gandhinagar KSEB EVCS - ChargeMOD,Kochi,Kerala,9.974193,76.293682,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,22.0
475,Vyttila KSEB EVCS - ChargeMOD,Vyttila,Keral,9.962902,76.319221,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,15.0
498,Kothamangalam KSEB EVCS - ChargeMOD,Kothamangalam,Kerala,10.053981,76.615384,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,22.0
510,Thodupuzha KSEB EVCS - ChargeMOD,Thodupuzha,Kerala,9.892123,76.708531,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,15.0
532,Moolamattom KSEB EVCS - ChargeMOD,Moolamattom,Kerala,9.789170,76.853857,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,15.0
543,Gandhi Nagar KSEB EVCS - ChargeMOD,Arpookara,Kerala,9.632684,76.524402,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,NaN
550,Pallam KSEB EVCS - ChargeMOD,Pallom,Kerala,9.543065,76.514231,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,15.0
555,Punnapra KSEB EVCS - ChargeMOD,Punnapra,Kerala,9.425617,76.346773,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,30.0
575,Pamba KSEB EVCS - ChargeMOD,Pamba,Kerala,9.412378,77.069969,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,15.0
599,Kundara KSEB - ChargeMOD,Kundara,Kerala,8.957186,76.671337,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,15.0
610,Kottiyam KSEB EVCS - ChargeMOD,Kottiyam,Kerala,8.866370,76.668878,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,15.0
614,Avananchery KSEB EVCS - ChargeMOD,Attingal,Kerala,8.690988,76.848398,ChargeMod (IN),Public - Membership Required,GB-T DC - GB/T 20234.3,15.0

In [23]:
df["Operator"].value_counts()

Operator
ChargeMod (IN)          355
GO EC (IN)              191
Zeon Charging            96
Tata Power               57
EESL (IN)                41
Chargezone (India)       24
(Unknown Operator)       10
Statiq (IN)               5
JIO BP Pulse (India)      5
Adani Gas-EV (TR)         4
Name: count, dtype: int64

In [24]:
df["Usage Type"].value_counts()

Usage Type
Public - Membership Required                  715
Public                                         58
Private - For Staff, Visitors or Customers     14
Public - Pay At Location                        1
Name: count, dtype: int64

In [25]:
df["Connector Type"].value_counts()

Connector Type
CCS (Type 2)                    504
CEE 3 Pin                       124
Type 2 (Tethered Connector)      85
CHAdeMO                          36
GB-T DC - GB/T 20234.3           34
Unknown                           3
IEC 60309 3-pin                   2
Name: count, dtype: int64

In [26]:
df.dropna(subset= "Power (kW)", inplace = True)

In [27]:
df.shape

(786, 9)

In [28]:
df.isna().sum()

Station Name      0
City              0
State             0
Latitude          0
Longitude         0
Operator          0
Usage Type        0
Connector Type    0
Power (kW)        0
dtype: int64

In [29]:
l = df.columns

In [30]:
for i in l :
    print(f"value counts of column {i}")
    print(df[i].value_counts())
    print()

value counts of column Station Name
Station Name
Flash Charge EVCS - ChargeMOD              5
Vadakkenchery KSEB EVCS - ChargeMOD        4
Thamarassery KESEB EVCS - ChargeMOD        4
Gandhi Road KSEB EVCS - ChargeMOD          4
Malappuram KSEB EVCS - ChargeMOD           4
                                          ..
Kay Pees Electricals (EVOK) - ChargeMOD    1
Indus Motors - ChargeMOD                   1
Trends Edavannappara EVCS - ChargeMOD      1
Mountainpass Residency - ChargeMOD         1
Sundaram Motors Coimbatore                 1
Name: count, Length: 487, dtype: int64

value counts of column City
City
Thiruvananthapuram     36
Thrissur               31
Kozhikode              27
Kannur                 10
Kayamkulam              9
                       ..
Kuttiyady               1
Panoor, Kannur          1
Hosdurg                 1
Melechowa               1
Coimbatore              1
Name: count, Length: 283, dtype: int64

value counts of column State
State
Kerala            707
Tamil Nadu         38
Keral              10
West Bengal         5
Maharashtra         4
Keraka              3
Lerala              3
Karnataka           3
Andhra Pradesh      2
uttar pradesh       2
Tamil Nadu          2
Karnataka           1
Uttar Pradesh       1
Telangana           1
Delhi               1
Madhya Pradesh      1
Puducherry          1
Kerala              1
Name: count, dtype: int64

value counts of column Latitude
Latitude
11.444087    4
9.976989     4
10.597238    4
8.690988     4
8.866370     4
            ..
11.144919    1
11.173280    1
11.168868    1
11.180744    1
10.918630    1
Name: count, Length: 498, dtype: int64

value counts of column Longitude
Longitude
75.955877    4
76.277811    4
76.479849    4
76.848398    4
76.668878    4
            ..
75.896170    1
75.902152    1
75.926769    1
75.851199    1
76.984610    1
Name: count, Length: 498, dtype: int64

value counts of column Operator
Operator
ChargeMod (IN)          354
GO EC (IN)              191
Zeon Charging            96
Tata Power               57
EESL (IN)                41
Chargezone (India)       24
(Unknown Operator)        9
Statiq (IN)               5
JIO BP Pulse (India)      5
Adani Gas-EV (TR)         4
Name: count, dtype: int64

value counts of column Usage Type
Usage Type
Public - Membership Required                  714
Public                                         58
Private - For Staff, Visitors or Customers     13
Public - Pay At Location                        1
Name: count, dtype: int64

value counts of column Connector Type
Connector Type
CCS (Type 2)                    504
CEE 3 Pin                       124
Type 2 (Tethered Connector)      85
CHAdeMO                          36
GB-T DC - GB/T 20234.3           33
Unknown                           2
IEC 60309 3-pin                   2
Name: count, dtype: int64

value counts of column Power (kW)
Power (kW)
30.0     295
60.0     151
3.3      128
22.0      50
25.0      42
7.4       31
24.0      29
15.0      25
50.0      11
80.0       6
20.0       3
120.0      3
40.0       2
90.0       2
7.0        2
7.2        1
7.5        1
3.2        1
150.0      1
9.0        1
45.0       1
Name: count, dtype: int64

In [31]:
df["State"].value_counts()

State
Kerala            707
Tamil Nadu         38
Keral              10
West Bengal         5
Maharashtra         4
Keraka              3
Lerala              3
Karnataka           3
Andhra Pradesh      2
uttar pradesh       2
Tamil Nadu          2
Karnataka           1
Uttar Pradesh       1
Telangana           1
Delhi               1
Madhya Pradesh      1
Puducherry          1
Kerala              1
Name: count, dtype: int64

In [40]:
df["State"] = df["State"].str.strip()

In [42]:
dic =  {
    "Keral" : "Kerala",
    "Keraka" : "Kerala",
    "Lerala" : "Kerala",
    "uttar pradesh" : "Uttar Pradesh",
}

In [43]:
df["State"] = df["State"].replace(dic)

In [44]:
df["State"].value_counts()

State
Kerala            724
Tamil Nadu         40
West Bengal         5
Maharashtra         4
Karnataka           4
Uttar Pradesh       3
Andhra Pradesh      2
Telangana           1
Delhi               1
Madhya Pradesh      1
Puducherry          1
Name: count, dtype: int64

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 786 entries, 0 to 854
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Station Name    786 non-null    object
 1   City            786 non-null    object
 2   State           786 non-null    object
 3   Latitude        786 non-null    float64
 4   Longitude       786 non-null    float64
 5   Operator        786 non-null    object
 6   Usage Type      786 non-null    object
 7   Connector Type  786 non-null    object
 8   Power (kW)      786 non-null    float64
dtypes: float64(3), object(6)
memory usage: 61.4+ KB

In [46]:
df["Operator"].value_counts()

Operator
ChargeMod (IN)          354
GO EC (IN)              191
Zeon Charging            96
Tata Power               57
EESL (IN)                41
Chargezone (India)       24
(Unknown Operator)        9
Statiq (IN)               5
JIO BP Pulse (India)      5
Adani Gas-EV (TR)         4
Name: count, dtype: int64

In [51]:
df[df["Operator"] == "(Unknown Operator)"]

,Station Name,City,State,Latitude,Longitude,Operator,Usage Type,Connector Type,Power (kW)
18,Shirdi,Shirdi,Maharashtra,19.757594,74.476347,(Unknown Operator),Public - Pay At Location,CCS (Type 2),30.0
706,Issacs Centre Square - Zeon,Sulthan Batheri,Kerala,11.661242,76.255681,(Unknown Operator),Public - Membership Required,CCS (Type 2),24.0
789,Mansavi SuperCharge Point,G B Nagar,Uttar Pradesh,28.455186,77.503585,(Unknown Operator),Public,CCS (Type 2),30.0
799,Village Vatika Restaurant And Hotel,Danora,Madhya Pradesh,21.885671,77.883991,(Unknown Operator),Public,CCS (Type 2),60.0
800,Vithal Kamats,Hinganghat,Maharashtra,20.574439,78.882304,(Unknown Operator),Public,CCS (Type 2),30.0
801,Hotel Bluemoon,Miduthuru,Andhra Pradesh,15.026219,77.621073,(Unknown Operator),Public - Membership Required,CCS (Type 2),150.0
802,Hotel Bluemoon,Miduthuru,Andhra Pradesh,15.026219,77.621073,(Unknown Operator),Public - Membership Required,CCS (Type 2),30.0
806,Mahalaxmi EV Charging STATION,Gautaum Buddha Nagar,Uttar Pradesh,28.547530,77.444910,(Unknown Operator),Public,Unknown,9.0
807,Mahalaxmi EV Charging STATION,Gautaum Buddha Nagar,Uttar Pradesh,28.547530,77.444910,(Unknown Operator),Public,CCS (Type 2),7.4

In [52]:
df["Usage Type"].value_counts()

Usage Type
Public - Membership Required                  714
Public                                         58
Private - For Staff, Visitors or Customers     13
Public - Pay At Location                        1
Name: count, dtype: int64

In [54]:
df["Connector Type"].value_counts()

Connector Type
CCS (Type 2)                    504
CEE 3 Pin                       124
Type 2 (Tethered Connector)      85
CHAdeMO                          36
GB-T DC - GB/T 20234.3           33
Unknown                           2
IEC 60309 3-pin                   2
Name: count, dtype: int64

In [56]:
df[df["Connector Type"]== "Unknown"]

,Station Name,City,State,Latitude,Longitude,Operator,Usage Type,Connector Type,Power (kW)
795,FC - JioBP - WBSDCL Athupur,Barrakpore,West Bengal,22.839467,88.385864,JIO BP Pulse (India),Public,Unknown,3.2
806,Mahalaxmi EV Charging STATION,Gautaum Buddha Nagar,Uttar Pradesh,28.547530,77.444910,(Unknown Operator),Public,Unknown,9.0

In [57]:
df["Power (kW)"].describe()

count    786.000000
mean      30.189186
std       20.289079
min        3.200000
25%       22.000000
50%       30.000000
75%       30.000000
max      150.000000
Name: Power (kW), dtype: float64

In [58]:
# IQR calculation

In [60]:
q1 = df["Power (kW)"].quantile(0.25)
q3 = df["Power (kW)"].quantile(0.75)

In [61]:
iqr = q3-q1

In [62]:
print(f"q1 is {q1}")
print(f"q3 is {q3}")
print(f"iqr is {iqr}")

q1 is 22.0
q3 is 30.0
iqr is 8.0

In [63]:
lb = q1 - 1.5*iqr
ub = q3 + 1.5*iqr

print(f"lower bound is {lb}")
print(f"upper bound is {ub}")

lower bound is 10.0
upper bound is 42.0

In [65]:
df[(df["Power (kW)"] < lb ) | (df["Power (kW)"] > ub)]

,Station Name,City,State,Latitude,Longitude,Operator,Usage Type,Connector Type,Power (kW)
0,Tata.ev Luxon Motors - Tata Power,Edappally,Kerala,10.011485,76.311387,Tata Power,Public - Membership Required,CCS (Type 2),60.0
2,Tata.ev Gokulam Motors - Tata Power,Choornikkara,Kerala,10.081303,76.339462,Tata Power,Public - Membership Required,CCS (Type 2),60.0
12,Tata.ev Hyson Motors - Tata Power,Thrissur,Kerala,10.496728,76.258361,Tata Power,Public - Membership Required,CCS (Type 2),60.0
17,Hotel Gokulam Sabari - Tata Power,Guruvayur,Kerala,10.596357,76.042934,Tata Power,Public - Membership Required,Type 2 (Tethered Connector),7.4
23,Tata.ev Store Malappuram,Malappuram,Kerala,11.052515,76.077640,Tata Power,Public - Membership Required,CCS (Type 2),60.0
...,...,...,...,...,...,...,...,...,...
846,Cafe Udupi Ruchi,Avinashi,Tamil Nadu,11.177190,77.283920,Zeon Charging,Public,CCS (Type 2),50.0
848,"Ibex River Resort, Pollachi",Pollachi,Tamil Nadu,10.646930,76.919920,Zeon Charging,Public,Type 2 (Tethered Connector),7.4
850,Adyar Ananda Bhavan Navakkarai,Navakkarai,Tamil Nadu,10.855920,76.862510,Zeon Charging,Public,CCS (Type 2),50.0
851,Adyar Ananda Bhavan Navakkarai,Navakkarai,Tamil Nadu,10.855920,76.862510,Zeon Charging,Public,CCS (Type 2),60.0
854,Sundaram Motors Coimbatore,Coimbatore,Tamil Nadu,10.918630,76.984610,Chargezone (India),Public,CCS (Type 2),45.0

In [66]:
df.shape

(786, 9)

In [67]:
df.isna().sum()

Station Name      0
City              0
State             0
Latitude          0
Longitude         0
Operator          0
Usage Type        0
Connector Type    0
Power (kW)        0
dtype: int64

In [69]:
df.duplicated().sum()

np.int64(0)

In [70]:
# connecting to SQL

In [71]:
import mysql.connector as connection

In [73]:
con = connection.connect(
    host = "localhost",
    user = "root",
    password =  "Nov@20242025"
)
print("Connection successfull")

Connection successfull

In [74]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

In [76]:
db_url = URL.create(
    drivername="mysql+pymysql",
    username= "root",
    password="Nov@20242025",
    host="localhost",
    port="3306",
    database="ev_db"
)
print(db_url)
engine = create_engine(db_url)

mysql+pymysql://root:***@localhost:3306/ev_db

In [78]:
df.to_sql(name = "Indian_EV_Stations_Simplified" , if_exists= "fail", index= False , con = engine )

C:\Users\HP\AppData\Local\Temp\ipykernel_2488\2264273411.py:1: UserWarning: The provided table name 'Indian_EV_Stations_Simplified' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  df.to_sql(name = "Indian_EV_Stations_Simplified" , if_exists= "fail", index= False , con = engine )

786